spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  application:
    name: storage
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql:storage}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

storage:
  config:
    bucket: flico-307e8.appspot.com
    key:
      #url: C:\Users\Cristopher Moccia\Desktop\FLICO\keyFlico\keyGoogleStorage.json
       url: /keys/key-firebase.json
      # url:/Users/antoninolatocca/Developer/Flico/keyGoogleStorage.json

url:
  flico:
    basePath: https://flico.it
  microservice:
    email:
      basePath: https://api.flico.it:8443/email/api/mail

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    liquibase: info
server:
  port: 8085